In [1]:
import pandas as pd

In [2]:
path_QQQ = "../data/CLEAN/QQQ_listo_entrenar_FINAL_READY.csv"
path_SPY = "../data/CLEAN/SPY_listo_entrenar_FINAL_READY.csv"

In [7]:
# ===== CARGAR DATOS =====
data_QQQ = pd.read_csv(path_QQQ, parse_dates=True)
data_SPY = pd.read_csv(path_SPY, parse_dates=True)

In [8]:
data_QQQ

,Date,Volume_Ratio_lag_5,RSI_14_lag_5,volume_change,Volume_Ratio_lag_3,ADX_14,daily_return,rolling_std_5d,Volume_lag_1,Volume_Ratio_lag_1,...,Volume_SMA_5,weekday,momentum_5d,RSI_14,MACD,return_3d,Open,month,MACD_diff_lag_3,target
0,2016-03-04,0.589011,55.040965,0.242626,0.641210,20.572457,0.000304,1.072870,25474600.0,0.843225,...,31410620.0,4,-6.94,41.319489,0.659611,-0.001214,105.75,3,-1.130143,0
1,2016-03-07,1.105183,38.526541,-0.183040,0.852847,20.735866,-0.006083,1.055524,31655400.0,1.007793,...,27236020.0,0,-0.52,40.031285,0.704445,-0.007601,105.13,3,-1.180920,0
2,2016-03-08,0.641210,34.919741,0.117446,0.843225,20.978216,-0.008263,0.692748,25861200.0,0.949522,...,28219900.0,1,0.87,38.309697,0.666928,-0.014042,104.30,3,-1.171572,1
3,2016-03-09,0.852847,41.566918,0.074360,1.007793,21.206452,0.006377,0.629341,28898500.0,1.024047,...,28587420.0,2,-1.01,40.434245,0.679393,-0.007969,104.54,3,-1.107042,0
4,2016-03-10,0.843225,41.211386,0.424792,0.949522,20.878555,-0.001533,0.553922,31047400.0,1.086051,...,32339720.0,3,-0.97,40.079269,0.669450,-0.003419,105.26,3,-1.052819,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,2024-12-18,1.350201,76.272089,0.914098,1.110776,45.372178,-0.036077,8.583422,28579100.0,0.984905,...,33524020.0,2,-13.45,58.652156,7.208823,-0.026087,535.15,12,2.498526,0
563,2024-12-19,0.946636,73.020686,-0.151022,1.135195,43.604966,-0.004448,11.069730,54703200.0,1.631761,...,38096880.0,3,-12.33,57.097860,5.857757,-0.044923,521.19,12,2.438527,1
564,2024-12-20,1.110776,74.405270,0.303352,0.984905,41.417253,0.008721,11.398857,46441800.0,1.219045,...,44446800.0,4,-11.87,59.361911,5.089056,-0.031804,510.44,12,1.972525,1
565,2024-12-23,1.135195,76.832650,-0.509784,1.631761,39.385804,0.009748,8.564726,60530000.0,1.361853,...,43985380.0,0,-15.30,61.417868,4.830853,0.014020,519.55,12,0.189632,1
566,2025-01-30,0.984905,74.473115,0.029356,1.219045,37.773929,0.004269,3.912005,29672800.0,0.674606,...,43755820.0,3,-12.75,61.507534,1.780998,0.017171,523.71,1,-1.238817,0

In [9]:
data_SPY

,Date,daily_return,Volume_Ratio_lag_5,Volume_Change,ADX_14,Stoch_Oscillator,Volume,RSI_14_lag_3,Volatility_10d,Volume_Ratio,...,RSI_14_lag_5,ATR_14,momentum_5d,Volume_lag_5,MACD_diff_lag_3,Volume_lag_3,month,weekday,SMA_50_was_imputed,target
0,2015-12-15,0.010496,0.768021,-0.155252,14.636267,45.972851,154069600.0,51.917385,2.450840,0.932446,...,53.448095,3.797931,-1.92,103372400.0,0.466669,116128900.0,12,1,0,1
1,2015-12-16,0.014634,1.117023,0.278753,13.660545,73.122172,197017000.0,46.392717,2.398207,1.144418,...,51.200600,3.783079,2.69,162401500.0,0.045131,211173300.0,12,2,0,0
2,2015-12-17,-0.015271,0.857871,-0.121434,12.733009,44.434389,173092500.0,47.918486,2.421909,0.943039,...,51.917385,3.772859,-1.01,116128900.0,-0.163606,182385200.0,12,3,0,1
3,2015-12-29,0.010659,1.519007,0.353585,11.871725,67.420814,92640700.0,51.051543,82.079337,0.579580,...,46.392717,3.712655,5.52,211173300.0,-0.156812,154069600.0,12,1,1,0
4,2016-03-02,0.004487,1.175979,-0.277749,12.928065,12.727273,102415000.0,55.144410,2.452361,0.711972,...,47.918486,4.172465,-3.90,182385200.0,0.040597,197017000.0,3,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,2024-12-16,0.004264,1.056391,0.216977,38.086006,94.070221,43695200.0,71.656957,1.831966,1.233938,...,71.553849,6.535962,2.11,34742700.0,1.271911,28677700.0,12,0,0,0
588,2024-12-17,-0.004113,1.065252,0.276422,37.650992,87.568270,55773500.0,68.541560,1.795887,1.425740,...,69.756545,6.347679,1.49,37234500.0,0.592374,31543800.0,12,1,0,0
589,2024-12-18,-0.029810,0.892504,0.940863,35.090154,40.728218,108248700.0,68.418745,6.283008,1.966972,...,71.656957,7.359988,-21.18,28677700.0,-0.014745,35904700.0,12,2,0,0
590,2024-12-19,-0.000309,0.964995,-0.206277,32.716781,1.076658,85919500.0,69.676790,8.212886,1.303621,...,68.541560,7.344989,-18.23,31543800.0,-0.372306,43695200.0,12,3,0,1
591,2025-02-20,-0.004157,1.067935,-0.772136,32.035886,94.967093,36554000.0,66.895978,144.680877,0.553528,...,68.418745,8.647490,6.17,35904700.0,-0.878050,55773500.0,2,3,1,0

In [14]:
qqq_julio_24 = data_QQQ[data_QQQ['Date'] <= '2024-07-18']
qqq_to_test = data_QQQ[data_QQQ['Date'] > '2024-07-18']

In [16]:
qqq_julio_24

,Date,Volume_Ratio_lag_5,RSI_14_lag_5,volume_change,Volume_Ratio_lag_3,ADX_14,daily_return,rolling_std_5d,Volume_lag_1,Volume_Ratio_lag_1,...,Volume_SMA_5,weekday,momentum_5d,RSI_14,MACD,return_3d,Open,month,MACD_diff_lag_3,target
0,2016-03-04,0.589011,55.040965,0.242626,0.641210,20.572457,0.000304,1.072870,25474600.0,0.843225,...,31410620.0,4,-6.94,41.319489,0.659611,-0.001214,105.75,3,-1.130143,0
1,2016-03-07,1.105183,38.526541,-0.183040,0.852847,20.735866,-0.006083,1.055524,31655400.0,1.007793,...,27236020.0,0,-0.52,40.031285,0.704445,-0.007601,105.13,3,-1.180920,0
2,2016-03-08,0.641210,34.919741,0.117446,0.843225,20.978216,-0.008263,0.692748,25861200.0,0.949522,...,28219900.0,1,0.87,38.309697,0.666928,-0.014042,104.30,3,-1.171572,1
3,2016-03-09,0.852847,41.566918,0.074360,1.007793,21.206452,0.006377,0.629341,28898500.0,1.024047,...,28587420.0,2,-1.01,40.434245,0.679393,-0.007969,104.54,3,-1.107042,0
4,2016-03-10,0.843225,41.211386,0.424792,0.949522,20.878555,-0.001533,0.553922,31047400.0,1.086051,...,32339720.0,3,-0.97,40.079269,0.669450,-0.003419,105.26,3,-1.052819,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
532,2024-06-18,0.886479,78.922776,-0.340469,1.002330,55.717915,0.000311,4.958904,37054500.0,1.296773,...,29051460.0,1,17.19,84.296495,9.700375,0.017744,485.01,6,0.035739,0
533,2024-06-20,1.380176,80.989468,0.387915,0.923546,55.638510,-0.007714,3.695220,24438600.0,0.841218,...,28928680.0,3,7.32,78.665518,9.752145,0.004838,486.42,6,0.073172,0
534,2024-06-21,1.002330,81.795405,0.162571,1.296773,55.368564,-0.002675,2.779869,33918700.0,1.172494,...,31643460.0,4,3.46,76.760861,9.579462,-0.010077,481.19,6,0.295957,0
535,2024-06-24,0.923546,82.560624,-0.042652,0.841218,54.152596,-0.011377,4.596404,39432900.0,1.246163,...,34519140.0,0,-5.23,68.188001,8.901839,-0.021766,478.18,6,0.257528,1
536,2024-07-18,1.296773,84.254520,-0.123006,1.172494,53.474916,-0.004733,4.063861,37751000.0,1.093625,...,36977720.0,3,-5.57,71.261093,5.804912,-0.033714,485.53,7,-0.191449,0

In [17]:
qqq_to_test

,Date,Volume_Ratio_lag_5,RSI_14_lag_5,volume_change,Volume_Ratio_lag_3,ADX_14,daily_return,rolling_std_5d,Volume_lag_1,Volume_Ratio_lag_1,...,Volume_SMA_5,weekday,momentum_5d,RSI_14,MACD,return_3d,Open,month,MACD_diff_lag_3,target
537,2024-09-04,0.841218,84.296495,-0.277427,1.246163,50.143512,-0.002588,8.615484,49347400.0,1.334517,...,38591020.0,2,-24.60,52.584302,0.404014,-0.021029,458.67,9,-0.717424,1
538,2024-09-05,1.172494,78.665518,0.059908,1.093625,47.140795,0.000938,9.646918,32505100.0,0.842297,...,38697760.0,3,-20.43,52.887161,-0.303243,-0.032022,458.97,9,-1.577072,0
539,2024-09-06,1.246163,76.760861,0.469401,1.334517,44.244273,-0.026799,12.154409,34452400.0,0.890294,...,40936060.0,4,-31.49,44.162393,-1.835102,-0.028450,460.33,9,-1.847345,1
540,2024-09-09,1.093625,68.188001,-0.348512,0.842297,41.554646,0.012873,11.578436,50624400.0,1.236670,...,39982100.0,0,-19.50,48.441903,-2.555675,-0.012988,453.06,9,-3.287618,1
541,2024-09-10,1.334517,71.261093,-0.100084,0.890294,38.626266,0.009239,5.175487,32981200.0,0.824899,...,36048680.0,1,-20.83,51.363928,-2.757654,-0.004687,456.24,9,-4.145913,1
542,2024-09-11,0.842297,52.584302,0.948868,1.236670,36.858243,0.021704,7.437021,29680300.0,0.823339,...,41116260.0,2,8.01,57.513349,-2.093932,0.043816,459.91,9,-5.400580,1
543,2024-09-12,0.890294,52.887161,-0.305439,0.824899,35.623049,0.009818,10.084786,57843000.0,1.406816,...,42260880.0,3,12.18,60.027112,-1.184704,0.040761,468.65,9,-5.669231,1
544,2024-09-13,1.236670,44.162393,-0.275384,0.823339,34.686126,0.004479,9.127672,40175500.0,0.950655,...,37958360.0,4,26.65,61.167443,-0.290526,0.036000,472.48,9,-5.393054,0
545,2024-09-16,0.824899,48.441903,-0.224177,1.406816,33.501345,-0.004417,6.702841,29111800.0,0.766940,...,35879240.0,0,18.78,59.360959,0.246629,0.009880,473.19,9,-4.409985,1
546,2024-09-17,0.823339,51.363928,0.332017,0.950655,32.739573,0.000531,2.488397,22585600.0,0.629489,...,35960060.0,1,14.83,59.514251,0.684609,0.000593,476.29,9,-3.367397,0
547,2024-09-18,1.406816,57.513349,0.326575,0.766940,32.142860,-0.004328,1.383539,30084400.0,0.836606,...,32373300.0,2,2.82,57.595729,0.857218,-0.008214,474.70,9,-2.492749,1
548,2024-09-19,0.950655,60.027112,0.322565,0.629489,32.210412,0.025292,4.673252,39909200.0,1.232781,...,34894700.0,3,10.14,64.717831,1.929580,0.021495,482.61,9,-2.032843,0
549,2024-09-20,0.766940,61.167443,-0.344902,0.836606,31.936761,-0.001912,5.639200,52782500.0,1.512622,...,35987880.0,4,7.10,63.826789,2.674369,0.019052,482.49,9,-1.702394,1
550,2024-09-23,0.629489,59.360959,-0.281531,1.232781,31.722402,0.002644,5.796031,34577700.0,0.960815,...,36439360.0,0,9.80,64.173231,3.328727,0.026024,482.95,9,-1.613308,1
551,2024-12-03,0.836606,59.514251,-0.260439,1.512622,33.453913,0.003076,17.198334,24843000.0,0.681763,...,34142060.0,1,43.38,77.346878,4.603463,0.022733,513.95,12,-0.784965,1
552,2024-12-04,1.232781,57.595729,0.402642,0.960815,35.292147,0.012362,20.458355,18597900.0,0.544721,...,31377460.0,2,51.82,78.923341,5.415905,0.026321,520.32,12,-0.354322,0
553,2024-12-05,1.512622,64.717831,-0.303478,0.681763,37.017729,-0.002780,20.898113,26086200.0,0.831367,...,24454880.0,3,38.45,77.603598,5.875045,0.012659,523.31,12,-0.097715,1
554,2024-12-06,0.960815,63.826789,0.307822,0.544721,38.719386,0.008958,17.810294,18169600.0,0.742985,...,22291860.0,4,44.04,78.831350,6.539556,0.018541,522.48,12,2.157242,0
555,2024-12-09,0.681763,64.173231,-0.129961,0.831367,40.123336,-0.007793,3.465090,23762600.0,1.065977,...,21458140.0,0,39.34,74.946831,6.659391,-0.001614,525.55,12,3.790444,0
556,2024-12-10,0.544721,77.346878,0.177785,0.742985,41.096412,-0.003399,2.218914,20674400.0,0.963476,...,22608560.0,1,3.73,73.259033,6.536192,-0.002233,523.62,12,4.439357,1
557,2024-12-11,0.831367,78.923341,0.321092,1.065977,42.244430,0.017900,3.869563,24350000.0,1.077026,...,23825040.0,2,6.66,76.272089,7.106265,0.006709,525.00,12,4.817766,0
558,2024-12-12,0.742985,77.603598,-0.267065,0.963476,43.310448,-0.006455,3.698524,32168600.0,1.350201,...,24906620.0,3,4.69,73.020686,7.199897,0.008046,527.68,12,4.436129,1
559,2024-12-13,1.065977,78.831350,0.220672,1.077026,44.497992,0.007659,4.427209,23577500.0,0.946636,...,25910180.0,4,4.05,74.405270,7.511889,0.019104,530.46,12,3.736063,1
560,2024-12-16,0.963476,74.946831,0.111169,1.350201,45.858111,0.014389,6.402783,28780400.0,1.110776,...,28171280.0,0,15.79,76.832650,8.277788,0.015593,533.08,12,3.572971,0
561,2024-12-17,1.077026,73.259033,-0.106342,0.946636,47.121079,-0.004399,4.719029,31979900.0,1.135195,...,29017100.0,1,15.20,74.473115,8.595254,0.017649,536.36,12,2.933812,0
562,2024-12-18,1.350201,76.272089,0.914098,1.110776,45.372178,-0.036077,8.583422,28579100.0,0.984905,...,33524020.0,2,-13.45,58.652156,7.208823,-0.026087,535.15,12,2.498526,0
563,2024-12-19,0.946636,73.020686,-0.151022,1.135195,43.604966,-0.004448,11.069730,54703200.0,1.631761,...,38096880.0,3,-12.33,57.097860,5.857757,-0.044923,521.19,12,2.438527,1
564,2024-12-20,1.110776,74.405270,0.303352,0.984905,41.417253,0.008721,11.398857,46441800.0,1.219045,...,44446800.0,4,-11.87,59.361911,5.089056,-0.031804,510.44,12,1.972525,1
565,2024-12-23,1.135195,76.832650,-0.509784,1.631761,39.385804,0.009748,8.564726,60530000.0,1.361853,...,43985380.0,0,-15.30,61.417868,4.830853,0.014020,519.55,12,0.189632,1
566,2025-01-30,0.984905,74.473115,0.029356,1.219045,37.773929,0.004269,3.912005,29672800.0,0.674606,...,43755820.0,3,-12.75,61.507534,1.780998,0.017171,523.71,1,-1.238817,0

In [19]:
spy_agosto_24 = data_SPY[data_SPY['Date'] <= '2024-08-27']
spy_to_test = data_SPY[data_SPY['Date'] > '2024-08-27']

In [20]:
spy_agosto_24

,Date,daily_return,Volume_Ratio_lag_5,Volume_Change,ADX_14,Stoch_Oscillator,Volume,RSI_14_lag_3,Volatility_10d,Volume_Ratio,...,RSI_14_lag_5,ATR_14,momentum_5d,Volume_lag_5,MACD_diff_lag_3,Volume_lag_3,month,weekday,SMA_50_was_imputed,target
0,2015-12-15,0.010496,0.768021,-0.155252,14.636267,45.972851,154069600.0,51.917385,2.450840,0.932446,...,53.448095,3.797931,-1.92,103372400.0,0.466669,116128900.0,12,1,0,1
1,2015-12-16,0.014634,1.117023,0.278753,13.660545,73.122172,197017000.0,46.392717,2.398207,1.144418,...,51.200600,3.783079,2.69,162401500.0,0.045131,211173300.0,12,2,0,0
2,2015-12-17,-0.015271,0.857871,-0.121434,12.733009,44.434389,173092500.0,47.918486,2.421909,0.943039,...,51.917385,3.772859,-1.01,116128900.0,-0.163606,182385200.0,12,3,0,1
3,2015-12-29,0.010659,1.519007,0.353585,11.871725,67.420814,92640700.0,51.051543,82.079337,0.579580,...,46.392717,3.712655,5.52,211173300.0,-0.156812,154069600.0,12,1,1,0
4,2016-03-02,0.004487,1.175979,-0.277749,12.928065,12.727273,102415000.0,55.144410,2.452361,0.711972,...,47.918486,4.172465,-3.90,182385200.0,0.040597,197017000.0,3,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,2024-06-20,-0.002714,1.510320,0.699718,36.617971,90.176322,70328200.0,71.517304,5.463650,1.393218,...,70.827488,6.088023,5.64,63251300.0,-0.436078,40089900.0,6,3,0,0
556,2024-06-21,-0.001352,1.002038,-0.082674,36.416100,79.614826,64513900.0,73.675032,5.057220,1.185273,...,71.350737,5.937450,2.06,44760900.0,-0.286844,55839500.0,6,4,0,1
557,2024-07-23,-0.001583,0.910245,-0.494471,37.166971,90.685966,34439600.0,74.348390,143.188514,0.646152,...,71.517304,6.386918,11.00,40089900.0,-0.211496,41376400.0,7,1,1,0
558,2024-07-29,0.000593,1.161750,-0.535718,36.089896,57.229561,39515800.0,72.215995,96.227121,0.789767,...,73.675032,6.720709,-2.34,55839500.0,-0.369719,70328200.0,7,0,1,1
559,2024-08-27,0.001368,0.843322,-0.725321,36.233888,98.333889,32693900.0,68.671375,152.072740,0.676916,...,74.348390,7.476373,13.07,41376400.0,-0.729021,64513900.0,8,1,1,0

In [22]:
spy_to_test

,Date,daily_return,Volume_Ratio_lag_5,Volume_Change,ADX_14,Stoch_Oscillator,Volume,RSI_14_lag_3,Volatility_10d,Volume_Ratio,...,RSI_14_lag_5,ATR_14,momentum_5d,Volume_lag_5,MACD_diff_lag_3,Volume_lag_3,month,weekday,SMA_50_was_imputed,target
560,2024-09-03,-0.020577,1.393218,-0.033493,35.233096,66.744419,60600100.0,73.822771,3.335136,1.307370,...,72.215995,7.803060,5.08,70328200.0,-0.443363,34439600.0,9,1,0,0
561,2024-09-04,-0.002048,1.185273,-0.220713,34.297658,62.979007,47224900.0,62.972384,4.250241,1.100945,...,68.671375,7.600699,6.44,64513900.0,-0.934645,39515800.0,9,2,0,0
562,2024-09-05,-0.002437,0.646152,-0.062692,33.128288,58.513829,44264300.0,71.403052,4.992127,0.986725,...,73.822771,7.536363,-4.17,34439600.0,-0.237243,32693900.0,9,3,0,0
563,2024-09-06,-0.016824,0.789767,0.547382,31.136593,4.067197,68493800.0,62.724326,7.356482,1.352152,...,62.972384,7.866623,-4.40,39515800.0,-0.507943,60600100.0,9,4,0,1
564,2024-09-09,0.011190,0.676916,-0.409497,29.287161,30.813439,40445800.0,61.760705,7.526653,0.774738,...,71.403052,7.829721,-15.15,32693900.0,-0.837205,47224900.0,9,0,0,1
565,2024-09-10,0.004360,1.307370,-0.100164,27.724888,41.335102,36394600.0,60.572325,7.314449,0.768391,...,62.724326,7.682598,-3.29,60600100.0,-1.197405,44264300.0,9,1,0,1
566,2024-09-11,0.010264,1.100945,1.067576,26.910160,66.224580,75248600.0,52.992193,6.710554,1.420605,...,61.760705,8.233841,3.47,47224900.0,-2.060183,68493800.0,9,2,0,1
567,2024-09-12,0.008412,0.986725,-0.310383,26.530916,86.870027,51892700.0,56.800078,6.793244,0.952245,...,60.572325,8.121424,9.48,44264300.0,-2.211633,40445800.0,9,3,0,1
568,2024-09-13,0.005236,1.352152,-0.242466,26.501104,95.676134,39310500.0,58.233417,7.235206,0.807887,...,52.992193,7.822751,21.65,68493800.0,-2.138468,36394600.0,9,4,0,1
569,2024-09-16,0.001473,0.774738,-0.067524,26.480622,98.859316,36656100.0,61.488573,7.097649,0.765255,...,56.800078,7.493269,16.43,40445800.0,-1.716071,75248600.0,9,0,0,1
570,2024-09-17,0.000413,0.768391,0.345506,26.777357,87.067060,49321000.0,63.995236,7.813317,0.976929,...,58.233417,7.371607,14.28,36394600.0,-1.154280,51892700.0,9,1,0,0
571,2024-09-18,-0.002976,1.420605,0.197155,27.239940,75.076923,59044900.0,65.507014,8.090385,1.249759,...,61.488573,7.406492,6.98,75248600.0,-0.643619,39310500.0,9,2,0,1
572,2024-09-19,0.017064,0.952245,0.275563,28.025626,94.318182,75315500.0,65.944729,9.299209,1.450339,...,63.995236,7.697457,11.89,51892700.0,-0.323687,36656100.0,9,3,0,0
573,2024-09-20,-0.001715,0.807887,0.029046,28.232695,86.154306,77503100.0,66.073210,7.843465,1.301084,...,65.507014,7.562639,6.24,39310500.0,-0.177625,49321000.0,9,4,0,1
574,2024-10-22,-0.000535,0.765255,-0.629477,29.556151,97.381269,34183800.0,64.179880,120.609254,0.578664,...,65.944729,8.183164,20.48,36656100.0,-0.269046,59044900.0,10,1,1,0
575,2024-10-30,-0.003027,0.976929,-0.205498,30.602582,90.035508,41435800.0,69.567241,143.435720,0.720665,...,66.073210,7.886510,16.94,49321000.0,0.214037,75315500.0,10,2,1,0
576,2024-11-01,0.004230,1.249759,-0.175550,30.237582,70.128717,45667500.0,66.497943,140.143574,0.833027,...,64.179880,7.993902,9.64,59044900.0,0.245800,77503100.0,11,4,1,1
577,2024-12-02,0.001787,1.450339,0.051979,31.584760,98.927906,31746000.0,73.459148,5.405234,0.688525,...,69.567241,9.800052,32.65,75315500.0,1.128415,34183800.0,12,0,0,1
578,2024-12-03,0.000467,1.301084,-0.152441,32.819318,99.362958,26906600.0,70.017858,5.108774,0.747656,...,66.497943,9.230048,35.66,77503100.0,1.322518,41435800.0,12,1,0,1
579,2024-12-04,0.006216,0.578664,0.590227,34.132371,99.632082,42787600.0,61.596528,5.259098,1.134688,...,73.459148,8.856473,24.34,34183800.0,0.710678,45667500.0,12,2,0,0
580,2024-12-05,-0.001656,0.720665,-0.327791,35.377480,96.734840,28762200.0,73.885782,4.653362,0.817712,...,70.017858,8.379582,26.65,41435800.0,2.276404,31746000.0,12,3,0,1
581,2024-12-06,0.001891,0.833027,0.086200,36.562015,97.460701,31241500.0,73.962873,4.292635,0.967565,...,61.596528,7.953184,36.77,45667500.0,3.057772,26906600.0,12,4,0,0
582,2024-12-09,-0.005149,0.688525,0.112069,37.204549,91.071792,34742700.0,75.026212,3.555914,1.056391,...,73.885782,7.655099,1.05,31746000.0,3.521036,42787600.0,12,0,0,0
583,2024-12-10,-0.003096,0.747656,0.071722,37.497391,87.013256,37234500.0,74.156488,2.925394,1.065252,...,73.962873,7.370449,-1.11,26906600.0,3.449475,28762200.0,12,1,0,1
584,2024-12-11,0.007730,1.134688,-0.229808,37.940006,96.662521,28677700.0,74.522261,2.872275,0.892504,...,75.026212,7.246131,-0.20,42787600.0,3.175793,31241500.0,12,2,0,0
585,2024-12-12,-0.005152,0.817712,0.099942,38.154639,89.202733,31543800.0,71.553849,2.055229,0.964995,...,74.156488,6.952122,-2.33,28762200.0,2.509395,34742700.0,12,3,0,0
586,2024-12-13,-0.000200,0.967565,0.138249,38.091490,88.929385,35904700.0,69.756545,1.881697,1.067935,...,74.522261,6.764113,-3.60,31241500.0,1.705836,37234500.0,12,4,0,1
587,2024-12-16,0.004264,1.056391,0.216977,38.086006,94.070221,43695200.0,71.656957,1.831966,1.233938,...,71.553849,6.535962,2.11,34742700.0,1.271911,28677700.0,12,0,0,0
588,2024-12-17,-0.004113,1.065252,0.276422,37.650992,87.568270,55773500.0,68.541560,1.795887,1.425740,...,69.756545,6.347679,1.49,37234500.0,0.592374,31543800.0,12,1,0,0
589,2024-12-18,-0.029810,0.892504,0.940863,35.090154,40.728218,108248700.0,68.418745,6.283008,1.966972,...,71.656957,7.359988,-21.18,28677700.0,-0.014745,35904700.0,12,2,0,0
590,2024-12-19,-0.000309,0.964995,-0.206277,32.716781,1.076658,85919500.0,69.676790,8.212886,1.303621,...,68.541560,7.344989,-18.23,31543800.0,-0.372306,43695200.0,12,3,0,1
591,2025-02-20,-0.004157,1.067935,-0.772136,32.035886,94.967093,36554000.0,66.895978,144.680877,0.553528,...,68.418745,8.647490,6.17,35904700.0,-0.878050,55773500.0,2,3,1,0

Export

In [23]:
qqq_julio_24.to_csv('../data/CLEAN/qqq_to_train.csv', index=False)
qqq_to_test.to_csv('../data/CLEAN/qqq_to_test.csv', index=False)
spy_agosto_24.to_csv('../data/CLEAN/spy_to_train.csv', index=False)
spy_to_test.to_csv('../data/CLEAN/spy_to_test.csv', index=False)